"""add customer password

Revision ID: 154a8afef0ab
Revises: aaa177234bdb
Create Date: 2026-09-22 16:04:14.450823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154a8afef0ab'
down_revision: Union[str, Sequence[str], None] = 'aaa177234bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'hashed_password')
    # ### end Alembic commands ###
