"""link transactions to cards

Revision ID: bfc1004029dd
Revises: 72dd33ded103
Create Date: 2026-09-23 17:14:45.654466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc1004029dd'
down_revision: Union[str, Sequence[str], None] = '72dd33ded103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_card_id'), 'transactions', ['card_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_card_id'), table_name='transactions')
    op.drop_column('transactions', 'card_id')
    # ### end Alembic commands ###
